name: Test self-hosted runner on Rocky Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Display system information
        run: |
          uname -a
